routes/web.php
<?php

use App\Http\Controllers\Admin\AuthorController;
use App\Http\Controllers\Admin\BookController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Front\BookMainPageController;
use App\Http\Controllers\Front\CommentController;
use App\Http\Controllers\Api\ApiBookController;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [BookMainPageController::class, 'index'])->name('books');
Route::get('/books/{id}', [BookMainPageController::class, 'show'])->name('books.show');
Route::post('/comment/create', [CommentController::class, 'create'])->name('comment.create');

Route::group(['prefix' => 'api'], function()
{
    Route::get('/books', [ApiBookController::class, 'index']);

});

Route::group(['prefix' => 'admin',  'middleware' => 'auth'], function()
{
    Route::resource('/book', BookController::class);
    Route::resource('/category', CategoryController::class);
    Route::resource('/user', UserController::class);
    Route::resource('/author', AuthorController::class);
    Route::post('logout', [UserController::class, 'logout'])->name('logout');

});

require __DIR__.'/auth.php';

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'slug'
    ];

    public static function getCategory()
    {
        return self::select('slug', 'title')->get();
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::paginate(10);
        return view('admin.category.index')->with('categories', $categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        Category::create($request->validated());
        return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('admin.category.edit')->with('category', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, $id)
    {
        Category::where('id', $id)->update($request->validated());
        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::destroy($id);
        return redirect()->route('category.index');
    }
}

resources/views/admin/category/create.blade.php
@extends('welcome')
<div><h2>Добавление категории</h2></div>
<form action="{{ route('category.store') }}" method="post">
    @csrf
    <div class="form-group">
        <input type="text" class="form-control" placeholder="категория" name="title" required>
    </div>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="тэг" name="slug" required>
    </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{{ route('category.index') }}">Отмена</a>
</form>

resources/views/admin/category/edit.blade.php
@extends('welcome')
<div><h2>Добавление категории</h2></div>
<form action="{{ route('category.update', $category->id) }}" method="post">
    @csrf
    @method('PUT')
    <div class="form-group">
        <input type="text" class="form-control" placeholder="категория" name="title" required
               value="{{ $category->title }}">
    </div>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="тэг" name="slug" required value="{{ $category->slug }}">
    </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{{ route('category.index') }}">Отмена</a>
</form>

resources/views/admin/category/index.blade.php
@extends('welcome')

@include('admin.nav')
<div>
    <button type="button" class="btn btn-success">
        <a href="{{ route('category.create') }}">
            <i class="fa fa-plus" aria-hidden="true"></i>
        </a>
    </button>
</div>
<table class="table">
    <thead>
    <tr>
        <th scope="col">Категория</th>
        <th scope="col">ТЭГ</th>
    </tr>
    </thead>
    <tbody>
    @foreach($categories as $category)
        <tr>
            <td>{{$category->title}}</td>
            <td>{{$category->slug}}</td>
            <td>
                <a href="{{ route('category.edit' , $category->id) }}" title="редактировать" class="btn btn-success">
                    <i class="fa-solid fa-pen-to-square"></i>
                </a>

                <form action="{{ route('category.destroy' , $category->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger" type="submit" onclick="alert('Удалить?')" title="удалить"><i
                            class="fa-sharp fa-solid fa-trash"></i>
                    </button>
                </form>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
<div>
    {{ $categories->links() }}
</div>