routes/web.php
<?php

use App\Http\Controllers\Admin\AuthorController;
use App\Http\Controllers\Admin\BookController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Front\BookMainPageController;
use App\Http\Controllers\Front\CommentController;
use App\Http\Controllers\Api\ApiBookController;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [BookMainPageController::class, 'index'])->name('books');
Route::get('/books/{id}', [BookMainPageController::class, 'show'])->name('books.show');
Route::post('/comment/create', [CommentController::class, 'create'])->name('comment.create');

Route::group(['prefix' => 'api'], function()
{
    Route::get('/books', [ApiBookController::class, 'index']);

});

Route::group(['prefix' => 'admin',  'middleware' => 'auth'], function()
{
    Route::resource('/book', BookController::class);
    Route::resource('/category', CategoryController::class);
    Route::resource('/user', UserController::class);
    Route::resource('/author', AuthorController::class);
    Route::post('logout', [UserController::class, 'logout'])->name('logout');

});

require __DIR__.'/auth.php';

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;

    const RAITING = [1, 2, 3, 4, 5];
    const IMAGE_URL = 'public/covers';
//
//    protected $fillable = [
//        'title',
//        'slug',
//        'description',
//        'rating',
//        'cover'
//    ];

    public function authors()
    {
        return $this->belongsToMany(Author::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function category()
    {
        return $this->hasOne(Category::class, 'slug', 'slug');
    }
}

app/Http/Controllers/Admin/BookController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\BookRequest;
use App\Models\Author;
use App\Models\Book;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;


class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::with('authors')->with('category')
            ->orderBy('id', 'DESC')
            ->paginate(10);
        return view('admin.book.index')->with('books', $books);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $authors = Author::all();
        return view('admin.book.create')->with('authors', $authors);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Book $book)
    {

        $authors = $request->input('author');
        $book->title = $request->input('title');
        $book->slug = $request->input('slug');
        $book->description = $request->input('description');
        $book->rating = $request->input('rating');

        $file = $request->file('cover');
        $path = Storage::put(Book::IMAGE_URL, $file);
        $book->cover = $path;
        $book->save();

        foreach ($authors as $author){
            $book->authors()->attach($author);
        }

        return redirect()->route('book.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = Book::findOrFail($id);
        return view('admin.book.edit')->with('book', $book);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(BookRequest $request, $id)
    {
        $authors = $request->input('author');

        Book::where('id', $id)->update($request->validated());
        $file = $request->file('cover');
        if (!empty($file)) {
            $path = Storage::put(Book::IMAGE_URL, $file);
            Book::where('id', $id)->update([
                'cover' => $path
            ]);
        }
        $book = Book::find($id);

        if (!empty($authors)) {
            $book->authors()->detach();
            foreach ($authors as $author){
                $book->authors()->attach($author);
            }
        }
        return redirect()->route('book.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Book::destroy($id);
        return redirect()->route('book.index');
    }
}

resources/views/admin/book/create.blade.php
@extends('welcome')
@php
    $rating = \App\Models\Book::RAITING;
    $slug = \App\Models\Category::getCategory();
@endphp
<div><h2>Добавление книги</h2></div>
<form action="{{ route('book.store') }}" method="post" enctype="multipart/form-data">
    @csrf
    <div class="form-group">
        <input type="text" class="form-control" placeholder="название" name="title" required>
    </div>
    <div class="form-group">
        <select name="slug">
            @foreach($slug as $item)
                <option value="{{ $item->slug }}">{{ $item->title }}</option>
            @endforeach
        </select>
    </div>
    <div class="form-group">
        <p>Автор</p>
        <select name="author[]" multiple>
            @foreach($authors as $author)
                <option value="{{ $author->id }}">{{ $author->name }}</option>
            @endforeach
        </select>
    </div>
    <div class="form-group">
        <textarea class="form-control" placeholder="описание" name="description" required
        ></textarea>
    </div>
    <div class="form-group">
        <select name="rating">
            @foreach($rating as $item)
                <option value="{{ $item }}">{{ $item }}</option>
            @endforeach
        </select>
    </div>
    <div class="form-group">
        <input type="file" class="form-control" placeholder="обложка" name="cover" required>
    </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{{ route('book.index') }}">Отмена</a>
</form>

resources/views/admin/book/edit.blade.php
@extends('welcome')
@php
    $slug = \App\Models\Category::getCategory();
    $authors = \App\Models\Author::getAuthor();
    $rating = \App\Models\Book::RAITING;

@endphp
<div><h2>Обновить книги</h2></div>
<form action="{{ route('book.update', $book->id) }}" method="post" enctype="multipart/form-data">
    @csrf
    @method("PUT")
    <div class="form-group">
        <input type="text" class="form-control" placeholder="название" name="title" required value="{{ $book->title }}">
    </div>
    <div class="form-group">
        <div><p>
                тэг: {{ $book->category->title }}
            </p></div>
        <select name="slug">
            <option value="{{ $book->category->slug }}"></option>
            @foreach($slug as $item)
                <option value="{{ $item->slug }}">{{ $item->title }}</option>
            @endforeach
        </select>
    </div>
    <div>
        @foreach($book->authors as $author)
                <span>{{ $author->name }}</span>
        @endforeach
    </div>

<p></p>
    <select name="author[]" multiple>
        @foreach($authors as $author)
                     <option value="{{ $author->id }}">{{ $author->name }}</option>
        @endforeach
    </select>
    <div class="form-group">
        <p></p>
        <span>рейтинг</span>
        <span> {{ $book->rating }}</span>
    </div>
    <div class="form-group">
        <select name="rating">
            <option value="{{ $book->rating }}"></option>
            @foreach($rating as $item)
                <option value="{{ $item }}">{{ $item }}</option>
            @endforeach
        </select>
    </div>
    <div class="form-group">
        <p>Описание</p>
        <textarea class="form-control" placeholder="описание" name="description" required
        >{{$book->description}}</textarea>
    </div>
    <div class="form-group">
        <input type="file" class="form-control" placeholder="обложка" name="cover" value="{{ $book->cover }}">
    </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{{ route('book.index') }}">Отмена</a>
</form>

resources/views/admin/book/index.blade.php
@extends('welcome')
@include('admin.nav')

<div>
    <button type="button" class="btn btn-success">
        <a href="{{ route('book.create') }}">
            <i class="fa fa-plus" aria-hidden="true"></i>
        </a>
    </button>
</div>
<table class="table">
    <thead>
    <tr>
        <th scope="col">Название</th>
        <th scope="col">ТЭГ</th>
        <th scope="col">Автор</th>
        <th scope="col">Описание</th>
        <th scope="col">Рейтинг</th>
        <th scope="col">Обложка</th>
    </tr>
    </thead>
    <tbody>
    @foreach($books as $book)
        @php
            $url = \Illuminate\Support\Facades\Storage::url($book->cover);
        @endphp
        <tr>
            <td>{{$book->title}}</td>
            <td>{{$book->category->title}}</td>
            <td>@foreach($book->authors as $author)
                    {{ $author->name }}</br>
                @endforeach</td>
            <td>{{$book->description}}</td>
            <td>{{$book->rating}}</td>
            <td><img src="{{$url}}" style="width: 50px; border-radius: 5px"></td>
            <td>
                <a href="{{ route('book.edit' , $book->id) }}" title="редактировать" class="btn btn-success">
                    <i class="fa-solid fa-pen-to-square"></i>
                </a>
                <form action="{{ route('book.destroy' , $book->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger" type="submit" onclick="alert('Удалить?')" title="удалить"><i
                            class="fa-sharp fa-solid fa-trash"></i>
                    </button>
                </form>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
<div>
    {{ $books->links() }}
</div>