routes/web.php
<?php

use App\Http\Controllers\Admin\AuthorController;
use App\Http\Controllers\Admin\BookController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Front\BookMainPageController;
use App\Http\Controllers\Front\CommentController;
use App\Http\Controllers\Api\ApiBookController;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [BookMainPageController::class, 'index'])->name('books');
Route::get('/books/{id}', [BookMainPageController::class, 'show'])->name('books.show');
Route::post('/comment/create', [CommentController::class, 'create'])->name('comment.create');

Route::group(['prefix' => 'api'], function()
{
    Route::get('/books', [ApiBookController::class, 'index']);

});

Route::group(['prefix' => 'admin',  'middleware' => 'auth'], function()
{
    Route::resource('/book', BookController::class);
    Route::resource('/category', CategoryController::class);
    Route::resource('/user', UserController::class);
    Route::resource('/author', AuthorController::class);
    Route::post('logout', [UserController::class, 'logout'])->name('logout');

});

require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;
     /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'is_staff',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::select('id', 'name', 'is_staff', 'email')->paginate(10);
        return view('admin.user.index')->with('users', $users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        User::create([
            'name' => $request->input('name'),
            'is_staff' => $request->input('is_staff'),
            'email' => $request->input('email'),
            'password' => Hash::make($request->input('password')),
        ]);
        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        return view('admin.user.edit')->with('user', $user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        User::where('id', $id)->update([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
        ]);
        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    }

    public function logout()
    {
        Auth::logout();
        return redirect('/');
    }
}

resources/views/admin/user/create.blade.php
@extends('welcome')


<div><h2>Добавление сотрудника или читателя</h2></div>
<form action="{{ route('user.store') }}" method="post">
    @csrf
    <div class="form-group">
        <input type="text" class="form-control" placeholder=" имя" name="name" required>
    </div>
    <div class="form-group">
        <select name="is_staff">
            <option value="1">Сотрудник</option>
            <option value="2">Читатель</option>
        </select>
    </div>
    <div class="form-group">
        <input type="email" class="form-control" placeholder="email" name="email" required>
    </div>
    <div class="form-group">
        <input type="password" class="form-control" placeholder="password" name="password" required>
    </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{{ route('user.index') }}">Отмена</a>
</form>

resources/views/admin/user/edit.blade.php
@extends('welcome')
<div><h2>Добавление сотрудника или читателя</h2></div>
<form action="{{ route('user.update', $user->id) }}" method="post">
    @csrf
    @method('PUT')
    <div class="form-group">
        <input type="text" class="form-control" placeholder="имя" name="name" required value="{{ $user->name }}">
    </div>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="категория" name="is_staff" required value="{{$user->is_staff == 1? 'сотрудник': 'читатель'}}">
    </div>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="email" name="email" required value="{{ $user->email }}">
    </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{{ route('user.index') }}">Отмена</a>
</form>

resources/views/admin/user/index.blade.php
@extends('welcome')
@include('admin.nav')

<div>
    <button type="button" class="btn btn-success">
        <a href="{{ route('user.create') }}">
            <i class="fa fa-plus" aria-hidden="true"></i>
        </a>
    </button>
</div>
<table class="table">
    <thead>
    <tr>
        <th scope="col">Имя</th>
        <th scope="col">Категория</th>
        <th scope="col">email</th>
    </tr>
    </thead>
    <tbody>
    @foreach($users as $user)
        <tr>
            <td>{{$user->name}}</td>
            <td>{{$user->is_staff == 1? 'сотрудник': 'читатель'}}</td>
            <td>{{$user->email}}</td>
            <td>
                <a href="{{ route('user.edit' , $user->id) }}" title="редактировать" class="btn btn-success">
                    <i class="fa-solid fa-pen-to-square"></i>
                </a>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
<div>
    {{ $users->links() }}
</div>